services:
  lab2:
    tty: true
    container_name: lab2
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=lab2_db
      - DB_PORT=5432
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
    depends_on:
      lab2_db:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - lab2

  lab2_db:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=stud
      - POSTGRES_PASSWORD=stud
      - PGDATA=/data/postgres
      - POSTGRES_DB=archdb
    volumes:
      - lab2_db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - lab2
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  lab2_db:

networks:
  lab2:
    driver: "bridge"
    external: false